# Default configuration (shared across all profiles)
spring:
  application:
    name: my-spring-boot-app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: org.h2.Driver

# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
server:
  port: 8080
logging:
  level:
    root: INFO
    com.example: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081
logging:
  level:
    root: INFO
    com.example: DEBUG

---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc:postgresql://staging-db-host:5432/stagingdb
    username: staging_user
    password: staging_password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
server:
  port: 8082
logging:
  level:
    root: INFO
    com.example: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/proddb
    username: prod_user
    password: prod_password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
server:
  port: 8080
logging:
  level:
    root: WARN
    com.example: WARN